# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

#name: Create and publish a Docker image

on:
  push:
    branches: master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: ghcr.io/joungsik/kakaobot:latest
          build-args: |
            MASTER_KEY=${{ secrets.MASTER_KEY }}

#  depely_heroku:
#    runs-on: ubuntu-latest
#
#    steps:
#      # Check-out your repository.
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Release a Docker container to Heroku.
#        uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          heroku_email: ${{ secrets.HEROKU_EMAIL }}
#          usedocker: true
#          docker_heroku_process_type: web
#          docker_build_args: |
#            MASTER_KEY
#        env:
#          MASTER_KEY: ${{ secrets.MASTER_KEY }}